const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let DATA=null,MODAL={type:null,id:null};
async function api(u,o={}){const headers=o.body instanceof FormData?{...(o.headers||{})}:{'Content-Type':'application/json',...(o.headers||{})};const r=await fetch(u,{...o,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2200)}
function fmtDate(v){try{return new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}catch{return v||''}}
async function refresh(){DATA=await api('/api/admin');render();}
function render(){if(!DATA)return;$('#handleIn').value=DATA.settings.handle||'';$('#subtitleIn').value=DATA.settings.subtitle||'';$('#avatarIn').value=DATA.settings.avatar_url||'';$('#today').textContent=new Date().toLocaleDateString([], {month:'short',day:'numeric',year:'numeric'});$('#stats').innerHTML=[['🔗',DATA.links.length,'Total Links'],['▣',DATA.media.length,'Images'],['◫',DATA.events.length,'Events'],['⚑',DATA.announcements.length,'Announcements']].map(x=>`<div class="stat"><div>${x[0]}</div><div class="num">${x[1]}</div><div class="label">${x[2]}</div></div>`).join('');$('#activity').innerHTML=(DATA.activity||[]).map(x=>`<div class="activity-row"><b>${esc(x.action)}</b><span>${esc(x.detail||'')} · ${fmtDate(x.created_at)}</span></div>`).join('')||'<div class="activity-row"><span>No activity yet.</span></div>';renderList('links',DATA.links);renderList('events',DATA.events);renderList('announcements',DATA.announcements);$('#mediaList').innerHTML=DATA.media.map(x=>`<div class="media-card"><img src="${esc(x.url)}" alt="${esc(x.name)}"><div class="name">${esc(x.name)}</div><button class="btn danger" data-action="media-delete" data-id="${esc(x.id)}">Delete</button></div>`).join('')||'<div class="panel">No images uploaded yet.</div>'}
function renderList(type,items){const el=$(`#${type==='links'?'linkList':type==='events'?'eventList':'noticeList'}`);el.innerHTML=items.map((x,i)=>{const published=!!x.published;let meta=type==='links'?x.url:type==='events'?[x.date_text,x.description].filter(Boolean).join(' · '):x.body;return `<div class="list-card" draggable="true" data-drag-type="${type}" data-id="${esc(x.id)}"><div><div class="item-title">${esc(x.title)}</div><div class="item-meta">${esc(meta||'')}</div></div><div class="item-actions"><button class="btn publish" data-action="toggle" data-type="${type}" data-id="${esc(x.id)}">${published?'Published':'Unpublished'}</button><button class="btn" data-action="edit" data-type="${type}" data-id="${esc(x.id)}">Edit</button><button class="btn danger" data-action="delete" data-type="${type}" data-id="${esc(x.id)}">Delete</button></div></div>`}).join('')||'<div class="panel">Nothing here yet.</div>';enableDrag(type)}
function enableDrag(type){const list=$(`#${type==='links'?'linkList':type==='events'?'eventList':'noticeList'}`);let drag;list.querySelectorAll('[data-drag-type]').forEach(el=>{el.addEventListener('dragstart',()=>{drag=el;el.style.opacity='.45'});el.addEventListener('dragend',()=>{el.style.opacity='';saveOrder(type)});el.addEventListener('dragover',e=>{e.preventDefault();if(drag&&drag!==el){const r=el.getBoundingClientRect();el.parentNode.insertBefore(drag,e.clientY<r.top+r.height/2?el:el.nextSibling)}})})}
async function saveOrder(type){const list=$(`#${type==='links'?'linkList':type==='events'?'eventList':'noticeList'}`);const ids=[...list.querySelectorAll('[data-id]')].map(x=>x.dataset.id);try{await api('/api/admin/reorder',{method:'POST',body:JSON.stringify({type,ids})});await refresh();toast('Order saved')}catch(e){toast(e.message)}}
function fields(type,x={}){if(type==='links')return `<div class="field"><label>Title<input name="title" required value="${esc(x.title)}"></label></div><div class="field"><label>URL<input name="url" required value="${esc(x.url)}" placeholder="https://..."></label></div><div class="field"><label>Icon type<select name="kind"><option value="" ${x.kind?'':'selected'}>Default</option><option value="instagram" ${x.kind==='instagram'?'selected':''}>Instagram</option><option value="ieee" ${x.kind==='ieee'?'selected':''}>IEEE</option><option value="globe" ${x.kind==='globe'?'selected':''}>Globe</option></select></label></div>`;if(type==='events')return `<div class="field"><label>Title<input name="title" required value="${esc(x.title)}"></label></div><div class="field"><label>Date / time<input name="date_text" value="${esc(x.date_text)}" placeholder="10 Oct 2026 · 5:00 PM"></label></div><div class="field"><label>Description<textarea name="description">${esc(x.description)}</textarea></label></div><div class="field"><label>Registration URL<input name="registration_url" value="${esc(x.registration_url)}" placeholder="https://..."></label></div><div class="field"><label>Image URL<input name="image_url" value="${esc(x.image_url)}" placeholder="/media/..."></label></div>`;return `<div class="field"><label>Title<input name="title" required value="${esc(x.title)}"></label></div><div class="field"><label>Announcement text<textarea name="body" required>${esc(x.body)}</textarea></label></div>`}
function openModal(type,id=null){const items=DATA[type==='links'?'links':type==='events'?'events':'announcements'];const x=id?items.find(a=>a.id===id):{};MODAL={type,id};$('#modalTitle').textContent=`${id?'Edit':'Add'} ${type==='links'?'Link':type==='events'?'Event':'Announcement'}`;$('#modalFields').innerHTML=fields(type,x);$('#modal').hidden=false;setTimeout(()=>$('#modalFields input')?.focus(),0)}
function closeModal(){$('#modal').hidden=true;MODAL={type:null,id:null}}
async function submitModal(e){e.preventDefault();const fd=new FormData(e.currentTarget),b=Object.fromEntries(fd.entries());const map={links:'links',events:'events',announcements:'announcements'},url=MODAL.id?`/api/admin/${map[MODAL.type]}/${MODAL.id}`:`/api/admin/${map[MODAL.type]}`;try{await api(url,{method:MODAL.id?'PUT':'POST',body:JSON.stringify(b)});closeModal();await refresh();toast('Saved successfully')}catch(x){toast(x.message)}}
async function deleteItem(type,id){if(!confirm('Delete this item?'))return;try{await api(`/api/admin/${type}/${id}`,{method:'DELETE'});await refresh();toast('Deleted')}catch(e){toast(e.message)}}
async function toggle(type,id){const items=DATA[type],x=items.find(a=>a.id===id);if(!x)return;try{await api(`/api/admin/${type}/${id}`,{method:'PUT',body:JSON.stringify({...x,published:!x.published})});await refresh();toast(x.published?'Unpublished':'Published')}catch(e){toast(e.message)}}
async function upload(){const f=$('#file').files[0];if(!f)return toast('Choose an image first');if(f.size>5*1024*1024)return toast('Maximum image size is 5 MB');try{const fd=new FormData();fd.append('file',f);await api('/api/media',{method:'POST',body:fd});$('#file').value='';await refresh();toast('Image uploaded')}catch(e){toast(e.message)}}
async function mediaDelete(id){if(!confirm('Delete this image?'))return;try{await api(`/api/media/${id}`,{method:'DELETE'});await refresh();toast('Image deleted')}catch(e){toast(e.message)}}
async function init(){try{DATA=await api('/api/admin');$('#login').hidden=true;$('#app').hidden=false;render()}catch{}$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#msg').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#login').hidden=true;$('#app').hidden=false;await refresh();toast('Signed in')}catch(x){$('#msg').textContent=x.message}});$('#logout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(a=>a.classList.remove('active'));n.classList.add('active');document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(`#${n.dataset.section}`).classList.add('active')}));$('#addLink').addEventListener('click',()=>openModal('links'));$('#addEvent').addEventListener('click',()=>openModal('events'));$('#addNotice').addEventListener('click',()=>openModal('announcements'));$('#modalForm').addEventListener('submit',submitModal);document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeModal));$('#upload').addEventListener('click',upload);$('#saveProfile').addEventListener('click',async()=>{try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({handle:$('#handleIn').value,subtitle:$('#subtitleIn').value,avatar_url:$('#avatarIn').value})});await refresh();toast('Profile saved')}catch(e){toast(e.message)}});document.body.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='edit')openModal(b.dataset.type,b.dataset.id);else if(a==='delete')deleteItem(b.dataset.type,b.dataset.id);else if(a==='toggle')toggle(b.dataset.type,b.dataset.id);else if(a==='media-delete')mediaDelete(b.dataset.id)})}
init();
