CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS links(id TEXT PRIMARY KEY,title TEXT NOT NULL,url TEXT NOT NULL,kind TEXT DEFAULT '',position INTEGER DEFAULT 0,published INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS announcements(id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,position INTEGER DEFAULT 0,published INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,title TEXT NOT NULL,date_text TEXT,description TEXT,registration_url TEXT,image_url TEXT,position INTEGER DEFAULT 0,published INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,name TEXT NOT NULL,url TEXT NOT NULL,mime TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity(id TEXT PRIMARY KEY,action TEXT NOT NULL,detail TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS login_attempts(ip TEXT NOT NULL,attempted_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity(created_at);
CREATE INDEX IF NOT EXISTS idx_login_ip_time ON login_attempts(ip,attempted_at);
